apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: b44yzz80k-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/b44yzz80k-java-springboot-gitops